# Generated by Django 4.0.3 on 2022-09-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate_proj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduateproject',
            old_name='content',
            new_name='title',
        ),
        migrations.AddField(
            model_name='graduateproject',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='graduateproject',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
