# Generated by Django 4.0.3 on 2022-09-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate_proj', '0002_rename_content_graduateproject_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduateproject',
            name='name',
        ),
        migrations.AddField(
            model_name='graduateproject',
            name='content',
            field=models.FileField(default='4', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='graduateproject',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
